- name: Install packages
  become: yes
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - git
      - unattended-upgrades
      - fail2ban
      - ufw
      - pwgen
      - snapd
      - nginx

- name: Add Docker apt key.
  become: yes
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
  register: add_repository_key

- name: Add Docker repository.
  become: yes
  apt_repository:
    repo: "deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Install Docker
  become: yes
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Install snap core/certbot
  become: yes
  ansible.builtin.command: "{{ item }}"
  with_items:
    - sudo snap install core
    - sudo snap refresh core
    - sudo snap install --classic certbot
    - sudo ln -s /snap/bin/certbot /usr/bin/certbot

- name: ufw enabled
  become: yes
  community.general.ufw:
    state: "enabled"
    policy: "deny"
    logging: "on"
    
- name: ufw rules
  become: yes
  community.general.ufw:
    rule: "allow"
    port: "{{ item }}"
    proto: "tcp"
  with_items:
    - "22"
    - "80"
    - "443"

- name: ufw allow only localhost to access port 4000
  become: yes
  community.general.ufw:
    rule: "allow"
    port: "4000"
    proto: "tcp"
    from_ip: 127.0.0.1

- name: Security measures
  become: yes
  shell: |
    echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
    sudo dpkg-reconfigure -f noninteractive unattended-upgrades
    sudo sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
    sudo systemctl restart sshd
    
- name: Get Barrel Wisdom repo for backend side of project
  ansible.builtin.git:
    repo: "https://github.com/CatClawed/barrelwisdom.git"
    dest: ~/barrelwisdom
    depth: 1
    version: dev

- name: Remove junk
  ansible.builtin.apt:
    name:
      - xinetd
      - nis
      - yp-tools
      - tftpd
      - atfpd
      - tftpd-hpa
      - rsh-server
      - rsh-redone-server
    state: absent
    autoclean: yes

- name: Copy credential script
  ansible.builtin.copy:
    src: files/generate-credentials.sh
    dest: ~/generate-credentials.sh
    mode: u+x

- name: Copy nginx settings
  become: yes
  ansible.builtin.copy:
    src: files/default.conf
    dest: /etc/nginx/conf.d/

- name: Change nginx file to match domain
  become: yes
  ansible.builtin.replace:
    path: /etc/nginx/conf.d/default.conf
    regexp: 'website\.com'
    replace: '{{ domain }}'

- name: Generate credentials
  ansible.builtin.command: ./generate-credentials.sh {{ user }}

- name: Certbot
  become: yes
  ansible.builtin.command: sudo certbot --non-interactive --nginx -d {{ domain }} --agree-tos -m curry@barrelwisdom.com