services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: always
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=barrelwisdom'
    volumes:
      - bw_database:/var/lib/postgresql/data:rw

  backend:
    container_name: backend
    build:
      context: ./barrelwisdom/backend
      dockerfile: Dockerfile.prod
    environment:
      - 'SECRET_KEY=${SECRET_KEY}'
      - 'DEBUG=${DEBUG}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'DB_USER=${DB_USER}'
    depends_on:
      - postgres
    volumes:
      - ./barrelwisdom/backend:/backend:rw
    restart: always

  frontend:
    container_name: frontend
    image: barrelwisdom/frontend:10-20.2
    restart: always
    ports:
      - 127.0.0.1:4000:4000

  memcached:
    container_name: memcached
    image: memcached:1.6.22-alpine3.18
    entrypoint:
      - memcached
      - -m 64
    restart: always

volumes:
  bw_database: {}